name: Check formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
            sudo apt-get update
            sudo apt-get install -y maven

      - name: Run spotless formatter
        run: mvn spotless:check
